-- MySQL master runner
SOURCE schema_mysql.sql;
SOURCE الأماكن_العامة_في_الفنادق.sql;
SOURCE الأمن_والسلامة.sql;
SOURCE قائمة_فحص_المولدات.sql;
SOURCE مظهر_موظفي_الفندق.sql;
SOURCE مكتب_الاستقبال.sql;
SOURCE اللياقة_البدنية.sql;
SOURCE حمام_السباحة.sql;
SOURCE الكوفي_شوب_بالفندق.sql;
SOURCE التشغيل_القياسية_للمطبخ.sql;
SOURCE التحقق_من_تنظيف_المطبخ.sql;
SOURCE التحقق_من_تفتيش_المطبخ.sql;
SOURCE قائمة_التحقق_من_تنظيف_الممرات.sql;
SOURCE تنظيف_الغرفة.sql;
SOURCE فحص_الغرفة.sql;
SOURCE المغسلة.sql;
SOURCE جرد_الفندق.sql;
SOURCE المتسوق_السري_في_الفنادق.sql;
